# Strava API Credentials Configuration
[sources.strava_source.strava.credentials]
client_id = "{{ env('CREDENTIALS__CLIENT_ID') }}"
client_secret = "{{ env('CREDENTIALS__CLIENT_SECRET') }}"
refresh_token = "{{ env('CREDENTIALS__REFRESH_TOKEN') }}"
access_token_url = "{{ env('CREDENTIALS__ACCESS_TOKEN_URL', 'https://www.strava.com/oauth/token') }}"